security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email # ✅ l'email est utilisé comme identifiant

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email # ✅ Symfony lit le champ "email"
        password_parameter: password
      logout:
        path: app_logout
        target: app_login
      remember_me: # facultatif, pour ajouter "se souvenir de moi"
        secret: "%kernel.secret%"
      entry_point: form_login

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
