vich_uploader:
  db_driver: orm
  mappings:
    user_avatar:
      uri_prefix: /uploads/avatars
      upload_destination: "%kernel.project_dir%/public/uploads/avatars"
      # optional:
      # allowed_mime_types: ['image/jpeg','image/png']
      # namer: Vich\UploaderBundle\Naming\UniqidNamer
